# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTMyZWM2N2UyYzk4MWI3OGFlNTc3MzFiNWQ5MTEzYWI3NWYxODZmNDllZjcwMDA3ZjQ1MzlkNjMxMjZkNTQ0Y2UwYTliZmMxZTdlMDM1MzUxYTdhM2Q0ZDBiYjc5MmVhYTk0MjcxMDJlZmZlZTdjNDgzOTU1MDY4YzgzMjM0MTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
